# Generated by Django 3.2.16 on 2023-01-16 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0003_alter_room_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='one',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='one', to=settings.AUTH_USER_MODEL),
        ),
    ]
