# Generated by Django 3.2.16 on 2022-12-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20221210_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedroom',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
