# Generated by Django 3.2.16 on 2022-12-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_bookedroom_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedroom',
            old_name='title',
            new_name='room',
        ),
    ]
