# Generated by Django 3.2.16 on 2022-12-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_title_bookedroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedroom',
            name='title',
            field=models.CharField(default='Встреча', max_length=50),
        ),
    ]
