# Generated by Django 3.2.16 on 2022-12-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='massage',
            new_name='message',
        ),
    ]
