# Generated by Django 3.2.16 on 2022-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_alter_notification_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='signals',
            field=models.BooleanField(default=False),
        ),
    ]
