# Generated by Django 3.2.16 on 2022-12-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rename_status_tasks_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
