# Generated by Django 3.2.16 on 2023-01-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.SmallIntegerField(choices=[(1, 'Активные таски'), (2, 'Backlog'), (3, 'Встречи'), (4, 'Выполненные таски'), (5, 'Незавершенные')], default=2)),
                ('description', models.TextField(null=True)),
                ('completed', models.PositiveSmallIntegerField(choices=[(1, 'Активный'), (2, 'Завершенный'), (3, 'Незавершенный')], default=1)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не срочно'), (2, 'Срочно'), (3, 'Очень срочно')], default=1)),
                ('deadline', models.DateField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
