# Generated by Django 3.2.16 on 2022-12-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(null=True)),
                ('completed', models.PositiveSmallIntegerField(choices=[(1, 'Активный'), (2, 'Завершенный'), (3, 'Незавершенный')])),
                ('date', models.DateField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не срочно'), (2, 'Срочно'), (3, 'Очень срочно')], null=True)),
                ('deadline', models.DateField(null=True)),
                ('category', models.ForeignKey(default='Входящие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='tasks.category')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
