# Generated by Django 3.2.16 on 2022-12-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_text_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не срочно'), (2, 'Срочно'), (3, 'Очень срочно')], default=1),
        ),
    ]
