# Generated by Django 3.2.16 on 2022-12-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.SmallIntegerField(choices=[(1, 'Активные таски'), (2, 'Backlog'), (3, 'Встречи'), (4, 'Выполненные таски'), (5, 'Незавершенные')], default=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
