# Generated by Django 3.2.16 on 2022-12-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20221209_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Активный'), (2, 'Завершенный'), (3, 'Незавершенный')], default=1),
        ),
    ]
